kind: Service
apiVersion: v1
metadata:
  name: pesbuk-service
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: php-pesbuk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesbuk-deployment
  labels:
    app: php-pesbuk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-pesbuk
      track: stable
  template:
    metadata:
      labels:
        app: php-pesbuk
        track: stable
    spec:
      containers:
      - name: php-pesbuk
        image: indradock/php-pesbuk:2.0
        ports:
        - containerPort: 80
        env:
            - name: DB_HOST
              value:"production.cge3wy8cu4rk.us-east-2.rds.amazonaws.com"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: p-secret-fb
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: p-secret-fb
                  key: password
            - name: DB_NAME
              value:"dbsosmed2"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pesbuk-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: pesbuktrial.indraku.online
    http:
      paths:
      #- path: /
      - backend:
          serviceName: pesbuk-service
          servicePort: 80
