kind: Service
apiVersion: v1
metadata:
  name: pesbuk-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: pesbuk-ku
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesbuk-deployment
  namespace: production
  labels:
    app: pesbuk-ku
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pesbuk-ku
      track: stable
  template:
    metadata:
      labels:
        app: pesbuk-ku
        track: stable
    spec:
      containers:
      - name: pesbuk-ku
        image: indradock/pesbuk-app:versi
        ports:
        - containerPort: 80
        env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysecretfb
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysecretfb
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysecretfb
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysecretfb
                  key: dbname
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pesbuk-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: pesbuk.indraku.online
    http:
      paths:
      #- path: /
      - backend:
          serviceName: pesbuk-service
          servicePort: 80
